### PR TITLE
Add configured_for relation

### PR DESCRIPTION
**Pull request by m0rsch1**

### CODE REVIEW

**Comment by m0rsch1** [comment]
The renaming of configured_models is not yet pushed.

**Comment by m0rsch1** [comment]
@Priyanka328 What do you think about overriding the setters to check if the domains are compatible, that means that only Software ComponentModels can be configured_for Assembly ComponentModels?

**Comment by Priyanka328** [comment]
> @Priyanka328 What do you think about overriding the setters to check if the domains are compatible, that means that only Software ComponentModels can be configured_for Assembly ComponentModels?

Yeah. I would agree with that. That will be clean I guess and we don't allow any other domain to use this relation.

**Comment by Priyanka328** [comment]
@m0rsch1 https://github.com/dfki-ric/xtypes/pull/8 
Are we on the same page with these changes?

**Comment by Priyanka328** [comment]
@m0rsch1 This is also ready to merge, right?

**Comment by m0rsch1** [comment]
Looks good to me

**Pull request merged**
